id: AIBO-5cl-mel16k
_target_: autrainer.datasets.AIBO

features_subdir: log_mel_16k
aibo_task: 5cl

standardize: true
path: data/AIBO/
features_path: data/AIBO/features/
index_column: file
target_column: class

file_type: npy
file_handler: autrainer.datasets.utils.NumpyFileHandler

criterion: autrainer.criterions.BalancedCrossEntropyLoss
metrics: 
  - autrainer.metrics.Accuracy
  - autrainer.metrics.UAR
  - autrainer.metrics.F1
tracking_metric: autrainer.metrics.UAR

transform:
  type: tabular
  base:
    - autrainer.transforms.Expand:
        size: 301
        axis: -2
  train:
    - autrainer.transforms.RandomCrop:
        size: 301
        axis: -2