id: AIBO-2cl-ComParE-llds
_target_: autrainer.datasets.AIBO

features_subdir: ComParE_2016-llds-v2
aibo_task: 2cl

standardize: true
path: data/AIBO/
features_path: data/AIBO/features/
index_column: file
target_column: class

file_type: npy
file_handler: autrainer.datasets.utils.NumpyFileHandler

criterion: autrainer.criterions.BalancedCrossEntropyLoss
metrics: 
  - autrainer.metrics.Accuracy
  - autrainer.metrics.UAR
  - autrainer.metrics.F1
tracking_metric: autrainer.metrics.UAR

transform:
  type: tabular
  base:
    - autrainer.transforms.Expand:
        size: 301
        axis: -2
  train:
    - autrainer.transforms.RandomCrop:
        size: 301
        axis: -2