id: MSPPodcast-mel16k
_target_: autrainer.datasets.MSPPodcast

features_subdir: log_mel_16k

path: data/MSP-Podcast/
features_path: data/MSP-Podcast/features/
index_column: FileName
target_column: EmoClass
categories:
  - A
  - H
  - N
  - S

file_type: npy
file_handler: autrainer.datasets.utils.NumpyFileHandler

criterion: autrainer.criterions.BalancedCrossEntropyLoss
metrics: 
  - autrainer.metrics.Accuracy
  - autrainer.metrics.UAR
  - autrainer.metrics.F1
tracking_metric: autrainer.metrics.UAR

transform:
  type: grayscale
  base:
    - autrainer.transforms.Expand:
        size: 301
        axis: -2
  train:
    - autrainer.transforms.RandomCrop:
        size: 301
        axis: -2