id: MSPPodcast-wav
_target_: autrainer.datasets.MSPPodcast

path: data/MSP-Podcast
features_subdir: Audios
index_column: FileName
target_column: EmoClass
categories:
  - A
  - H
  - N
  - S

file_type: wav
file_handler: autrainer.datasets.utils.AudioFileHandler

criterion: autrainer.criterions.BalancedCrossEntropyLoss
metrics: 
  - autrainer.metrics.Accuracy
  - autrainer.metrics.UAR
  - autrainer.metrics.F1
tracking_metric: autrainer.metrics.UAR

transform:
  type: raw
  train:
    - autrainer.transforms.RandomCrop:
        size: 48000